### ISSUE TITLE
[FEAT]希望增加链接预览功能

### ISSUE THREAD

**Issue by aligod6** [Privoce/vocechat-web#100]
**简述**
希望增加链接预览功能

**你预期要达到什么效果**
发送网址链接自动预览信息，如果是图片自动显示图片

**目前有没有替代**
Rocket.Chat

**附加信息**

**Comment by zerosoul** [comment]
目前有链接预览功能   是没起作用吗？方便的话，贴一下你发的链接是啥，我试试。
如果是图片自动显示图片，这个功能暂时没有。
