### ISSUE TITLE
[FEAT]能把chatgpt接入机器人吗？

### ISSUE THREAD

**Issue by liuwx2010** [Privoce/vocechat-web#107]
**简述**
能把chatgpt接入机器人吗？

**你预期要达到什么效果**
这样就可以通过机器人和chatgpt聊天了

**目前有没有替代**
现在已经有人吧chatgpt接入微信等其他聊天工具了，技术上应该不难

**附加信息**
你的想法的截图，或者您的联系方式，等等

**Comment by zerosoul** [comment]
目前可以借助已有的 bot+webhook机制，自行接入chatGPT

**Comment by zerosoul** [comment]
可以试试这个： https://github.com/Privoce/vocechat-chatbot-vercel
