### ISSUE TITLE
[BUG] api/swagger 页面关闭 

### ISSUE THREAD

**Issue by suqier-sec** [Privoce/vocechat-web#111]
**描述问题**
api/swagger apidoc如何关闭，安全隐患很大，普通用户也能访问

使用代码部署的修改哪里关闭这个文档，使用docker部署的又改修改哪里

常规的是再 Spring Boot 应用程序的 application.properties 文件中将springfox.documentation.swagger-ui.enabled=false 即可，我们这里也是一样吗

**附加信息**
联系方式，备注，等等，可不填

**Comment by zerosoul** [comment]
这不是bug，是特性，OpenAPI Doc体现的就是Open，已经做好权限控制，比如很多敏感信息，都需要登录认证，更敏感的，需要admin登录认证。
不过你说的加一个开关，我们可以考虑一下。
