### ISSUE TITLE
[FEAT] 机器人建议

### ISSUE THREAD

**Issue by oyzbmmmm** [Privoce/vocechat-web#114]
**简述**

1. 机器人名称[油箱]，可以修改
2. 机器人可以有撤回消息的API
3. 增加斜杠/命令，或者针对发送回的消息能附加回调按钮组，增加交互
4. ~~机器人可以支持reply消息类型的API~~ (最新版已支持)

**你预期要达到什么效果**
以下是对应以上消息的效果
1. 有时候，名称不满意，可随时修改
2. 针对，有些触发关键词可以撤回，一些提示消息可以撤回
3. 点击按钮后，能附加一个请求字段来传回此消息的相关JSON串，来执行某些特定动作，比如点击撤回按钮后传回消息ID，进行撤回操作
4. 在群聊中可以针对每条消息对应回复，以避免造成不知道消息是发给谁的

**目前有没有替代**
你的想法在某个产品中，是否已经有了，请列出

**附加信息**
你的想法的截图，或者您的联系方式，等等

**Comment by zerosoul** [comment]
web最新版，机器人名称可以改了
