### ISSUE TITLE
[求助]docker部署后网页只显示not found

### ISSUE THREAD

**Issue by Lyviecs** [Privoce/vocechat-web#115]
**Describe the bug**
如题，我是用docker命令部署的，部署后打开配置网页只出现“not found”字样，docker中的日志显示“web client updated”进程在重复进行（是在与s.voce.chat通信正常的情况下）
在访问网页时日志显示“request{remote_addr=172.17.0.1 version=HTTP/1.1 method=GET uri=/}: poem::middleware::tracing_mw: error status=404 Not Found error=not found duration=15.207262ms”，因本人并非专业人员，无法自行解决此问题，特此求助

**Screenshots**
截图如下
![屏幕截图 2023-05-18 035137](https://github.com/Privoce/vocechat-web/assets/41200032/09c6beb3-8805-469f-8ba8-4a3bdd732031)
![屏幕截图 2023-05-18 035122](https://github.com/Privoce/vocechat-web/assets/41200032/b0074337-c912-4420-b93e-9d48a58eda29)

**DockerDesktop**
本人使用的是windows平台的docker desktop，不确定是否与此相关

**CLI**
docker run --name="vocechat" -p 3603:3000 -v D:\Docker\vocechat\data:/home/vocechat-server/data -d --restart=unless-stopped privoce/vocechat-server:latest

**Comment by zerosoul** [comment]
这个大概率是你使用层面的问题，可以加我v看看  yanggc_2013

**Comment by Lyviecs** [comment]
> 这个大概率是你使用层面的问题，可以加我v看看 yanggc_2013

抱歉一直没有回复，我又尝试了一下，不再试图直接挂载到磁盘，而是改为挂载到数据卷，不再有这样的情况了
这样看来，应该是权限的问题
我并不了解这方面的知识，冒昧打扰了
