### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ding-jiaqi** [Privoce/vocechat-web#117]
**Describe the bug**
web 端，点击发送按钮没反应

**To Reproduce**
1、输入内容
2、点击发送按钮

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: edge
 - Server Version [e.g. v0.3.1]
 - Client Version [e.g. v0.3.26]

**Additional context**
F12 没有看到报错，也没有发送请求，猜测应该是由于某种原因，click 事件没有执行

**Comment by zerosoul** [comment]
感谢反馈，已修复，将在下个版本更新发布。
