### ISSUE TITLE
[BUG]我部署之后发现非管理员设置里可以看到”成员”和“数据管理”，而在官方演示版本中则没有这问题

### ISSUE THREAD

**Issue by xtayaitak** [Privoce/vocechat-web#124]
**描述问题**
[BUG]非管理员设置里可以看到”成员”和“数据管理”

![image](https://github.com/Privoce/vocechat-web/assets/4498459/35f63c3c-e852-4157-b6b8-1f5ce209965d)

**Comment by zerosoul** [comment]
fixed 请更新到web client 最新版本  @xtayaitak
