### ISSUE TITLE
[Question]请问如何使用NPM反代

### ISSUE THREAD

**Issue by 740527654** [Privoce/vocechat-web#155]
如题，直接反代的话会报502。请问该怎么设置呢

**Comment by RoeWade** [comment]
你说的是 nginx 反代吗？https://doc.voce.chat/install/install-by-docker

**Comment by 740527654** [comment]
> 你说的是 nginx 反代吗？https://doc.voce.chat/install/install-by-docker

我使用的是[Nginx Proxy Manager]这个DOCKER，已经根据提示的参数进行设置，但不知为何仍然无法访问
![微信截图_20231102075717](https://github.com/Privoce/vocechat-web/assets/63200055/5fa91190-0f01-4267-a4a9-ce8da8e6b417)
![微信截图_20231102075735](https://github.com/Privoce/vocechat-web/assets/63200055/be98937e-457e-4a2a-938d-0840b0539728)
![微信图片_20231102075653](https://github.com/Privoce/vocechat-web/assets/63200055/98cc19c9-e5b9-4766-9eca-02a0f7ae01d8)

**Comment by RoeWade** [comment]
你的 nginx 反代指向了局域网IP的 3017 端口，vocechat-server(docke)监听的是 3000 端口，检查一下你的 docker 有没有将 vocechat-server 容器的 3000 端口映射到本机的 3017 端口。

**Comment by 740527654** [comment]
已经映射了3017端口，但是仍然不起作用，局域网IP能正常访问，但是用域名就不行。是不是其它某个参数也要再修改呢

**Comment by RoeWade** [comment]
尝试以下排查步骤：
假定你的域名 domain.com
服务器外网 IP: 5.5.5.5，内网 IP: 192.168.1.5, docker ip: 172.17.0.1

从外网往内往逐步排查端口是否正确返回数据。
从本机 curl -k https://5.5.5.5:443
在服务器上 curl http://127.0.0.1:3017
进入 docker curl http://127.0.0.1:3000
...

**Comment by 740527654** [comment]
我现在将vocechat的网络模式变更为custom br0 192.168.3.48。
电脑通过IP 192.168.3.48:3000可以直接访问，
外网如果通过端口转发也可以访问vocechat，
npm的docker curl vocechat的内网地址也正常，但是如果通过反代访问依然会显示502 bad gateway，curl -k也不行

**Comment by RoeWade** [comment]
那直接用 nginx 试试？我怀疑是不是 NPM 的问题？docker 的网络是桥接的，复杂度会增加一点。

**Comment by 740527654** [comment]
的确是NPM的问题，我换了一个docker源后就可以正常访问了。因为配置其它反代没有发现过异常所以没往这方面想，辛苦了！
