### ISSUE TITLE
[BUG] 新建channel点击markdown按钮报错

### ISSUE THREAD

**Issue by hywlzx** [Privoce/vocechat-web#174]
**描述问题**
新建channel点击输入框的markdown按钮后，页面显示
![image](https://github.com/Privoce/vocechat-web/assets/19977607/820516bc-220b-472f-ad51-da861f01c312)
重新进入channel、注销后重新登陆、docker服务重启、删除原有channel重新创建依然无法解决。
进入无痕模式访问页面才能正常进入channel。

**如何复现**
复现步骤举例：
1. 新建channel
2. 进入channel后直接点击输入框的markdown按钮
3. 报上述截图错误

**预期结果**
点击markdown按钮正常显示对应效果

**环境信息**
 - 操作系统: win10
 - 浏览器 chrome  122.0.6261.129
 - 版本: vocechat-server 0.3.44

**Comment by RoeWade** [comment]
请问这个问题和 #172 有关系吗？

**Comment by hywlzx** [comment]
和172没有关系，172我使用其他方式解决了。这个是我目前遇到的问题

**Comment by zerosoul** [comment]
> 和172没有关系，172我使用其他方式解决了。这个是我目前遇到的问题

请贴一下 web客户端 的版本号，这个问题在v0.7.4已经处理。

**Comment by hywlzx** [comment]
我之前没有看过版本号，现在重新试一下好了，不知道是不是更新了。
