### ISSUE TITLE
docker方式在oracle cloud的arm服务器上安装报错

### ISSUE THREAD

**Issue by selsunblue** [Privoce/vocechat-web#18]
`mkdir -p ~/.vocechat-server/data
docker run -d --restart=always \
  -p 443:443 \
  --name vocechat-server \
  -v ~/.vocechat-server/data:/home/vocechat-server/data \
  privoce/vocechat-server:latest \
  --network.bind "0.0.0.0:443" \
  --network.domain "url" \
  --network.tls.type "acme_tls_alpn_01" \
  --network.tls.acme.cache_path "/home/vocechat-server/data/cert"`
privoce/vocechat-server:latest改成privoce/vocechat-server:latest-arm64都会显示WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested，后面添加--platform linux/amd64 \参数后没有上面报错，但是运行不起来，查看日志是这样的
`exec /docker-entrypoint.sh: exec format error
exec /docker-entrypoint.sh: exec format error
exec /docker-entrypoint.sh: exec format error
exec /docker-entrypoint.sh: exec format error
exec /docker-entrypoint.sh: exec format error
exec /docker-entrypoint.sh: exec format error
exec /docker-entrypoint.sh: exec format error
exec /docker-entrypoint.sh: exec format error
exec /docker-entrypoint.sh: exec format error
exec /docker-entrypoint.sh: exec format error`

**Comment by stilleshan** [comment]
官方 docker 镜像都不支持 arm64 肯定不行.

**Comment by zerosoul** [comment]
> 看错了,有arm64版本.
> 
> 但是 OS/ARCH 上还是 amd64, 可能作者上传了错误版本镜像

arm64确实有问题，今天更新了，可以试试。记得拉取的时候，把`latest`标签改为`latest-arm64` @selsunblue
