### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by free521521521** [Privoce/vocechat-web#183]
通过 docker 将vocechat 安装在本地 CentOS 上，本地访问没问题。
当我使用域名+端口的方式从外网访问，页面灰色持续弹出：
getInitialized: Failed to fetch
getLoginConfig: Failed to fetch
getServer: Failed to fetch

![Screenshot 2024-05-05 at 03 58 16](https://github.com/Privoce/vocechat-web/assets/47398199/0c26ce9b-0ecd-4834-8552-aabf97c1344b)

我防火墙开了端口，路由器做了转发，都校对过没问题了。且用同网络下另一台 nas 新建 docker 也一样。

**Comment by RoeWade** [comment]
用 Chorme 开发者工具（F12）看一下，网络里是否存在不同域的请求，导致了请求失败。

**Comment by free521521521** [comment]
发现了在反向代理中：

```
    if ($scheme = http) {
        return 301 https://$host$request_uri; 
```
        
没有提现https的端口，修改成：

```
    if ($scheme = http) {
        return 301 https://$host:端口$request_uri; 
```

问题解决
