### ISSUE TITLE
[BUG] docker部署存在一直重新加载的严重BUG

### ISSUE THREAD

**Issue by sky22333** [Privoce/vocechat-web#185]
目前我使用的是最新版docker镜像，部署完成后进入web端，在第二步填入注册管理员账户后，会跳回第一步
此时我删除后缀，重新进，账户已经注册成功，然后进入设置页面的概览选项会一直自动重新加载，严重影响使用

**Comment by Jonasfeng** [comment]
碰到一样的问题。
http://IP:port/#/setting/路径可正常进入显示；
http://IP:port/#/setting/overview、http://IP:port/#/setting/third_app、http://IP:port/#/setting/login_method的页面出现无限刷新加载页面的情况，另外挂载好服务器映射到公网后，服务器运行一段时间后会断连，所有设备均无法访问，过一段时间后使用域名+端口的方式访问，页面灰色持续弹出：get Initialized: Failed to fetch、get LoginConfig: Failed to fetch、get Server: Failed to fetch重启docker后可短暂恢复，但过一段时间后服务器仍然出现断连情况。

**Comment by RoeWade** [comment]
确实存在这个问题，正在修复中。

**Comment by RoeWade** [comment]
https://hub.docker.com/r/privoce/vocechat-server/tags

先使用上一个版本 v0.3.44
