### ISSUE TITLE
两个关于移动设备访问邀请链接的问题

### ISSUE THREAD

**Issue by Nigh** [Privoce/vocechat-web#20]
反馈两个问题。

1. Android设备访问Play商店下载页面时，没有自动跳转至本地的Play商店app。
2. iOS设备访问邀请注册链接时，会直接跳转至下载页面，导致无法在iOS上注册。

**Comment by shuotwang** [comment]
1. 这个问题尝试替换了跳转链接，但测试中跳转情况不稳定。暂时在新版本中使用这个链接，稍后如果有稳定解决方案再更新；
2. 更新了手机访问邀请链接的网页排布，完全显示了原来在页面下方的跳转入口。

如有其他体验问题也可再开新 issue 反馈。
