### ISSUE TITLE
[FEAT] Add French support

### ISSUE THREAD

**Issue by PhilGoud** [Privoce/vocechat-web#204]
**Is your feature request related to a problem? Please describe.**
I have started translation using locales but the messages times (X minutes ago) stays in english, strangely enough.

**Describe the solution you'd like**
Add times to locales please ?

**Describe alternatives you've considered**
Maybe i missed it

**Additional context**
[fr.zip](https://github.com/user-attachments/files/17017264/fr.zip)

**Comment by zerosoul** [comment]
thank you, added French and fixed message time at v0.7.42, publish it later~
