### ISSUE TITLE
[FEAT] Database in Plain text. Hash Passwords please.

### ISSUE THREAD

**Issue by SnowyYT07** [Privoce/vocechat-web#211]
Well, I'm not the first guy to notice that the password in the database is in plain text. In some cases, this can be a vulnerability issue.

I want an update that brings one of the following: MD5, SHA256, Bcrypt, or Argon2.
I and probably more users are concerned about the security making users change for other big applications when used on a large scale or with a big friend group or other things, as mentioned in an issue[[55]](https://github.com/Privoce/vocechat-web/issues/55) report a user wrote 

> [Furthermore, user passwords in the database are stored in clear text... Therefore, my suggestion is that if you want to use it commercially or in large quantities, it is recommended to move to a more mature project. ](https://github.com/Privoce/vocechat-web/issues/55#:~:text=%E5%A4%A7%E5%AE%B6%E8%87%AA%E8%AF%81-,%E5%8F%A6%E5%A4%96%2C%20%E6%95%B0%E6%8D%AE%E5%BA%93%E9%87%8C%E7%9A%84%E7%94%A8%E6%88%B7%E5%AF%86%E7%A0%81%E5%B1%85%E7%84%B6%E6%98%AF%E6%98%8E%E6%96%87%E5%AD%98%E5%82%A8%E7%9A%84...%20%E6%89%80%E4%BB%A5%E6%88%91%E7%9A%84%E5%BB%BA%E8%AE%AE%E6%98%AF%E5%A6%82%E6%9E%9C%E4%BD%A0%E7%9C%9F%E7%9A%84%E6%83%B3%E5%95%86%E7%94%A8%E6%88%96%E5%A4%A7%E6%89%B9%E9%87%8F%E4%BD%BF%E7%94%A8%2C%20%E5%BB%BA%E8%AE%AE%E6%8D%A2%E4%B8%80%E4%B8%AA%E6%9B%B4%E6%88%90%E7%86%9F%E7%9A%84%E9%A1%B9%E7%9B%AE.,-Add%20a%20comment)

**Comment by RoeWade** [comment]
Thank you for pointing it out. It has been fixed in the latest version(v0.3.56). 

docker run -d --restart=always \
-p 3000:3000 \
--name vocechat-server \
privoce/vocechat-server:latest
