### ISSUE TITLE
[BUG]无法接入vocechat ChatGPT机器人

### ISSUE THREAD

**Issue by MasterKe2003** [Privoce/vocechat-web#216]
使用https://github.com/Privoce/vocechat-chatbot-vercel#readme
中的本地nodejs环境部署，可以看到ChatGPT有回复，但是发送一直有问题，使用postman调试接口可以发送成功消息，但是程序就是一直等待响应
如果程序正在发送的时候我使用postman也是发不出去，只要一中断程序，postman马上通了
![image](https://github.com/user-attachments/assets/d6b7cf66-73f6-4078-a34c-eb9610e410fd)
下面是postman调试发的消息
![image](https://github.com/user-attachments/assets/a29daefd-ffbd-4de1-9d88-d1c27aeb9120)

程序有ChatGPT的回复，发送消息的时候报错这个
bot: start req ChatGPT
bot: error [TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))]
bot: failed to parse JSON response [SyntaxError: Unexpected end of JSON input] 
调试了一下看到response好像是空的

下面是vocechat的日志（docker部署）
2024-10-27T08:43:55.190570Z  INFO request{remote_addr=172.17.0.1 version=HTTP/1.1 method=POST uri=/api/bot/reply/75}: poem::middleware::tracing_mw: error status=401 Unauthorized error=401 Unauthorized duration=117.128µs

附上我的环境变量设置：
![image](https://github.com/user-attachments/assets/27ee1823-a43c-48dd-a222-13337cc937cb)
机器人id【#2】和【2】都试过了

**Comment by RoeWade** [comment]
将 data/key.json 改个名字试一下？
可能 key.json 这个文件里的 server_key 这个字段数据不正常。

{"server_id":"xnBYJ4yHC0n7Gyxxxxx","server_key":"v1cBKihgu9JOnuxxxxx","third_party_secret":"CszY1DxFjxxxxx"}

**Comment by MasterKe2003** [comment]
> 将 data/key.json 改个名字试一下？ 可能 key.json 这个文件里的 server_key 这个字段数据不正常。
> 
> {"server_id":"xnBYJ4yHC0n7Gyxxxxx","server_key":"v1cBKihgu9JOnuxxxxx","third_party_secret":"CszY1DxFjxxxxx"}

改成啥呀

**Comment by MasterKe2003** [comment]
![image](https://github.com/user-attachments/assets/56d74e32-2f95-4cfc-a2ec-5a14b232e5f1)
还有这个错误

**Comment by RoeWade** [comment]
改名后，服务端重启了吗？服务端返回的信息看一下？还是不是 401 ？

**Comment by MasterKe2003** [comment]
> 改名后，服务端重启了吗？服务端返回的信息看一下？还是不是 401 ？

改成啥呀

**Comment by MasterKe2003** [comment]
> 改名后，服务端重启了吗？服务端返回的信息看一下？还是不是 401 ？

![image](https://github.com/user-attachments/assets/3ac8e729-fe1b-445e-ad41-7a8403a2719e)
我d的是这样的

**Comment by RoeWade** [comment]
随便改一个名字：
mv data/key.json data/key.json.backup

**Comment by MasterKe2003** [comment]
> mv data/key.json data/key.json.backup

![image](https://github.com/user-attachments/assets/02fbf247-bd9b-4e6b-8189-17480a16acab)
还是一样，已经重启了docker  restart vocechat-server和[vocechat-chatbot-vercel](https://github.com/Privoce/vocechat-chatbot-vercel#readme)

**Comment by RoeWade** [comment]
收到，我们查一下代码。
