### ISSUE TITLE
能否设置定期清理聊天记录

### ISSUE THREAD

**Issue by figwh** [Privoce/vocechat-web#23]
能否像 rocketchat 一样可以对消息进行裁剪？或者定期清理聊天记录，这样可以减小服务器的压力，谢谢

**Comment by zerosoul** [comment]
目前：可以设置自动删除的时间
![image](https://user-images.githubusercontent.com/2985895/218901909-e056e297-eb03-4237-91ac-bf0d1e30094f.png)

**Comment by figwh** [comment]
收到，谢谢
