### ISSUE TITLE
Request Not Allowed ，无法初始化

### ISSUE THREAD

**Issue by Aqaao** [Privoce/vocechat-web#27]
Login failed: null
Failed to sign up: null
Request Not Allowed

![图片](https://user-images.githubusercontent.com/110408568/204584068-547296a0-84a9-4134-80f4-864e7fea2b28.png)

注册失败

**Comment by Aqaao** [comment]
删除容器重新run就好了，之前好像也没动什么东西啊🤔

**Comment by zerosoul** [comment]
> 

@Aqaao   我们复现了这个问题，不过不确定你也是同样的情况：邮箱地址里面含有大写吗？

**Comment by Aqaao** [comment]
> > 
> 
> @Aqaao 我们复现了这个问题，不过不确定你也是同样的情况：邮箱地址里面含有大写吗？

有，后面用的是个乱输的假邮箱，没想到是因为这个。

**Comment by zerosoul** [comment]
> 

嗯  我们马上会发布一个新版本 会加上这个修复  大小写不敏感
