### ISSUE TITLE
vocechat-server的Docker无法在arm64服务器上运行

### ISSUE THREAD

**Issue by StephenEvenson** [Privoce/vocechat-web#33]
服务器的CPU是Ampere Altra，架构为aarch64，系统为Ubuntu 22.04.1
报错如下：
![报错信息](https://user-images.githubusercontent.com/39738893/204844180-1f277aba-0881-4ff0-9c50-9d1fe2d7afa4.png)

**Comment by Showfom** [comment]
Docker 的镜像都是 AMD64 的，当然无法在 ARM64 用了

https://hub.docker.com/r/privoce/vocechat-server/tags

你可以自己打包嘛

**Comment by StephenEvenson** [comment]
我知道，但他镜像的tag是有arm64的，那个`latest-arm64`，推的镜像却是amd64，群里说镜像能在arm上运行，但我拉的latest-arm64的运行不了呀，感觉是启动脚本`docker-entrypoint.sh`的问题。

**Comment by zerosoul** [comment]
> 我知道，但他镜像的tag是有arm64的，那个`latest-arm64`，推的镜像却是amd64。

没错，不过之前arm64确实有问题，今天更新了，可以试试。记得拉取的时候，把`latest`标签改为`latest-arm64`

**Comment by StephenEvenson** [comment]
确实已经可以了
