### ISSUE TITLE
Invite link always shows generating

### ISSUE THREAD

**Issue by wolgy** [Privoce/vocechat-web#38]
<img width="492" alt="image" src="https://user-images.githubusercontent.com/30134245/205230826-bb245a43-7ef7-4b60-b87f-ceffa8415333.png">
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/30134245/205231171-6e856fbb-a52c-481c-a72e-ef0285101343.png">

In my case,the invite link always shows generating.But the generating request is 200 and returns the correct invite link.
This seems to be a frontend issue

**Comment by wolgy** [comment]
客户端版本: 0.3.26
服务器端版本: 0.3.1

**Comment by zerosoul** [comment]
不应该，可以贴出来访问地址吗，或者可以加我v具体了解一下

**Comment by zerosoul** [comment]
感谢反馈，虽然是部署环节的传参问题，但是我们也兼容了这种情况，将在客户端0.3.28修复此问题
