### ISSUE TITLE
通过使用shell安装的，使用过程中出现Request Not Found

### ISSUE THREAD

**Issue by fireworksdancewindsing** [Privoce/vocechat-web#40]
我是通过shell安装的。安装的时候域名为空，然后通过宝塔建了个网站反代访问的。
使用都没有问题，注册什么都正常。但是呢，在聊天窗口中只要切换频道就会出现Request Not Found。
出现这个，页面显示是正常的。只是会以一个提醒的方示出来。像手机新来消息一样。
每切换个频道必出现。

**Comment by zerosoul** [comment]
嗯 目前shell脚本安装 存在版本问题  我们正在看

**Comment by fireworksdancewindsing** [comment]
请问一下大佬。如果后续更新了，我shell安装的要怎么更新吖？直接用官方代码重新安装麽？谢谢。

**Comment by zerosoul** [comment]
shell安装版本问题已fix，可以先stop，或者杀死进程，重新安装即可。
