### ISSUE TITLE
自动切换语言

### ISSUE THREAD

**Issue by SurpriseLon** [Privoce/vocechat-web#47]
当ip为国外或者浏览器语言为英文的访问者可以看到英文的页面

When the ip is outside of China or the browser language is English visitors can see the page in English

**Comment by zerosoul** [comment]
> 当ip为国外或者浏览器语言为英文的访问者可以看到英文的页面
> 
> When the ip is outside of China or the browser language is English visitors can see the page in English

指的是：假设如果用户设置的偏好语言是英语，他访问的默认就是英语界面，中文，日文亦然？

**Comment by SurpriseLon** [comment]
> > 当ip为国外或者浏览器语言为英文的访问者可以看到英文的页面
> > When the ip is outside of China or the browser language is English visitors can see the page in English
> 
> 指的是：假设如果用户设置的偏好语言是英语，他访问的默认就是英语界面，中文，日文亦然？现在应该就是这样的，如果不是，请v我：yanggc_2013，排查下

感谢大大的回复，我的意思是可以根据ip，访问者使用的语言来自动切换
比如说我ip在日本，然后进网站显示的是日语
我ip在美国，则显示的是英语

**Comment by zerosoul** [comment]
哦 这个意思 根据IP去判断国家  或者用第三方服务 或者自有数据库吧  有推荐吗？
