### ISSUE TITLE
消息管理的建议[FEAT]

### ISSUE THREAD

**Issue by SoraKasvgano** [Privoce/vocechat-web#48]
已部署到树莓派，十分轻量，点赞。
目前的问题有：

1.sqlite是否有切片与体积管理设置。
2.聊天记录可否针对服务器全局/频道分开设置 消息（图片/文字/视频/文档）有效期，比如超过7天附件自动销毁，15天聊天记录自动销毁。
3.20个人license不是很够用，免费license人数限制太狠了，建议参考免费QQ群人数，当前的人数限制下如果将微信群和QQ群好友介绍来的话将会十分棘手。
4.关于大文件传输，是否可以让浏览器充当P2P打洞工具，甚至可以设置好本地工作文件夹，如果双方都在线的话，可以利用浏览器互相传输文件。
5.提供OSS onedrive挂载功能。
6.提供URL网页预览功能是否可以更进一步，提供网页截图预览（可关闭）。

**Comment by zerosoul** [comment]
大赞，反馈已收到，我们会逐条考虑~ 欢迎加我v yanggc_2013 实时探讨

**Comment by SurpriseLon** [comment]
希望能加一个自动切换语言的功能 :)
