### ISSUE TITLE
[FEAT]token的有效时间能设置吗

### ISSUE THREAD

**Issue by ChaosTong** [Privoce/vocechat-web#49]
token的有效时间能设置吗, 300秒太短了, 想要写一个bot, 用于自动发消息. 看到有刷新方式, 但是那bot每次发消息基本就是两条接口连着调用了, 先刷新token再发送消息.

**Comment by zerosoul** [comment]
目前不能，token时长短是出于安全考虑，只能结合refreshToken机制，来持久使用token
