### ISSUE TITLE
[BUG]更新最新WEB版本后，生成邀请链接URL错误

### ISSUE THREAD

**Issue by sniper54** [Privoce/vocechat-web#51]
**描述问题**
请用简洁清晰的语言描述您遇到的问题

**如何复现**
复现步骤举例：
1. 在设置页面
2. 点击成员
3. 显示 的URL链接为默认的[HTTPS://1.2.3.4:4000](http://1.2.3.4:4000/?magic_token=XXXXXXX

**预期结果**
应该为https://myurl.com/magic_token=xxxxx
![屏幕截图 2022-12-08 154059](https://user-images.githubusercontent.com/25277487/206387825-50641f51-6ebb-460d-a83c-1a1c4f521d7d.png)

**截图**
如果可以，请附上截图（注意保护隐私信息）

**环境信息**
 - 操作系统: [e.g. iOS]
 - 浏览器 [e.g. chrome, safari]
 - 版本 [e.g. 客户端v0.3.26,服务端v0.3.1]

**附加信息**
联系方式，备注，等等，可不填

**Comment by zerosoul** [comment]
这是部署环节没有设置 frontend_url 参数导致的问题，我们先暂时兼容处理下这种情况。
