### ISSUE TITLE
网页端能做一个移动版界面吗？

### ISSUE THREAD

**Issue by dsgler** [Privoce/vocechat-web#53]
**简述**
现在手机上用浏览器访问页面不正常

**你预期要达到什么效果**
直接网页访问可以降低用户使用门槛，而且这应该也不是很难

**目前有没有替代**
虽然有app，但是50M的大小还是让人望而却步，显得有些多余

**附加信息**
你的想法的截图，或者您的联系方式，等等

**Comment by zerosoul** [comment]
目前暂时没有适配移动端的计划，当初就是按照PC使用场景做的，完全适配移动端，需要不少工作。

**Comment by suhan1996** [comment]
有前端经验的话欢迎开源贡献mobile web版本 @dsgler

**Comment by benny-tse** [comment]
手机端的界面基本无法使用，没有针对移动端做优化，建议借鉴tailchat的移动端界面，这样会方便很多！

**Comment by zerosoul** [comment]
@benny-tse  @dsgler  做了个初步适配，可以在此体验下  https://privoce.voce.chat/

**Comment by benny-tse** [comment]
> 

的确有进步，比原来实用性好很多！但是点击输入框的时候，页面自动放大，这是不错的。但是输入完毕点击发送，页面无法自动缩小，以至于需要手动将页面缩小才能看到侧边栏。
