### ISSUE TITLE
[FEAT]Api是否可以订阅新消息，Server主动推送新消息到指定URL，可以实现Bot相关的功能

### ISSUE THREAD

**Issue by BloodGuan** [Privoce/vocechat-web#54]
我希望实现聊天Bot的一些功能。
找了一圈Api文档，貌似没有发现可以订阅新消息的接口。
是否是我看漏了。
如果真的没有，是否可以增加一个这样的功能？

**Comment by zerosoul** [comment]
目前没有，正在规划webhook功能，应该能满足需求~

**Comment by BloodGuan** [comment]
感觉可以规划一下BotApi相关功能，前期可以提供简单的webhook之类的供我们轻度使用，静候佳音：）

**Comment by zerosoul** [comment]
已加：https://doc.voce.chat/zh-cn/bot-and-webhook

**Comment by yan1990** [comment]
> 已加：https://doc.voce.chat/zh-cn/bot-and-webhook

打不开了。。  楼主的意思，应该是觉得目前由于地区限制问题，无法收到推送。  如果支持新消息来了后，触发api事件，也可以间接的满足需求了。
