### ISSUE TITLE
上传大文件Nginx返回错误413未提示及处理[BUG]

### ISSUE THREAD

**Issue by wolgy** [Privoce/vocechat-web#57]
在网页端上传大文件（40+Mb）时，由于上传大小超过限制。Nginx会返回错误413 Request Entity Too Large。
这个时候预期的情况应该是提示错误并停止传输。
但是实际情况是上传还在继续，并且上传完成后在聊天页面上会显示相应文件。造成上传成功的假象。

**Comment by suhan1996** [comment]
Try change your ngnix.conf client_max_body_size to 500M? The client side might need to do some changes accordingly. @zerosoul web client might need to show an error message to 413, something like "File size too large".

**Comment by zerosoul** [comment]
ok，上传是有做分片上传机制，这个问题可以两个方面都做下优化：
- 分片最小单位不要超过nginx默认的大小限制
- 给出413类型提示，并终止上传
