### ISSUE TITLE
[FEAT]希望增加手机网页端的适配

### ISSUE THREAD

**Issue by kyuuketsu** [Privoce/vocechat-web#63]
**简述**
希望增加适配移动设备的网页端。

**你预期要达到什么效果**
手机需要下载app让大多数人望而却步，使用网页端有利于方便推广软件。手机网页端只需要简单接受消息和发送文字即可，其他功能可以在app端使用。

**Comment by suhan1996** [comment]
For those who have front-end experience, welcome to contribute to a responsive mobile web version based on the current codebase!

**Comment by zerosoul** [comment]
做了初步适配，可以在此体验下：https://privoce.voce.chat/
