### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mabisi** [Privoce/vocechat-web#64]
**Describe the error**
Succinctly describe what the error is.

**Reproduce**
Steps to reproduce the behavior.
1. Go to "..." .
2. Click on '....' .
4. See the error

**Expected behavior**
Succinctly describe what you expect to happen.

**Installation completes and then loads infinitely without access**

**Screenshot**
![image](https://user-images.githubusercontent.com/19968269/210752610-67875360-8505-4753-b2fe-da439dd3be60.png)

**Desktop (please fill in the following information):**
 - Operating System. [e.g. iOS] windows
 - Browser [e.g. chrome, safari] chrome
 - Server version [e.g. v0.3.1]  v0.3.18
 - Client version [e.g. v0.3.26

**Additional background**
Add any additional context about the issue here.

Startup parameters
```
docker run -d --restart=always \
  -p 3000:3000 \
  --name vocechat-server \
  -v /opt/vocechat-server/data:/home/vocechat-server/data \
  privoce/vocechat-server:v0.3.18-arm64 \
  --network.frontend_url "https://*" 
```
have been requesting.
https://*/api/user/events?api-key=eyJhbGciOiJIUzI1NiJ9. eyJkIjp7InVpZCI6MSwiZGV2aWNlIjoid2ViOjFTTlZyTUhFN2JwampyM3VqVkU4SSIsImlzX2FkbWluIjp0cnVlLCJpc19ndWVzdCI6ZmFsc2V9LCJlIjoiMjAyMy0wMS0wNVQwOTo1OTo1MC45NDA4MzIzNTZaIiwibiI6IjNQWVRPR3FldG1NQUFBQUEiLCJ0IjoiQWNjZXNzVG9rZW4ifQ .DxNJNd7yvThkmOWY8NBAN793U9sXOOeS9mVHp7rCd0Y&users_version=1

**Comment by Mabisi** [comment]
Refresh page prompt
![image](https://user-images.githubusercontent.com/19968269/210782686-2a45d9f3-446d-4b5b-83a4-f8cc1a4c337d.png)

**Comment by zerosoul** [comment]
经排查 是API走CDN的问题  需自行解决  再观察
