### ISSUE TITLE
中国的服务器centos，centos已经有梯子，但是还不能有消息推送。

### ISSUE THREAD

**Issue by ouyangyansen** [Privoce/vocechat-web#65]
中国的服务器centos，centos已经有梯子，但是还不能有消息推送。
现在来了消息根本就收不到，一个聊天工具，没有消息提醒就像老虎没有牙齿。

**Comment by loszhang** [comment]
我是用的是香港服务器，网络也是可以访问谷歌的，也是不能收到消息推送

**Comment by RoeWade** [comment]
一楼的梯子客户端姿势是 socks 方式? 还是 http 代理？还是 12345 全局透明代理 + iptables？
