### ISSUE TITLE
iOS客户端推送失效了？[BUG]

### ISSUE THREAD

**Issue by BloodGuan** [Privoce/vocechat-web#66]
之前的iOS版本推送是正常的，貌似更新之后就没有推送了，不知道是我服务器设置问题还是iOS客户端的问题？

**Comment by shuotwang** [comment]
新版本（0.2.66）已经更新。修复了Google service 正常情况下有关推送的问题，以及添加了在 google service 连接异常时提示推送不可用的弹窗提醒。
