### ISSUE TITLE
能否增加类似微信的好友添加功能

### ISSUE THREAD

**Issue by ray0019** [Privoce/vocechat-web#68]
当前的用户列表都是公开的，任何已经注册的成员都可以向其他人发信息。这对于公司内部通讯是没问题的。
但是对于个人通讯来说并不妥当，没有了好友机制和公开化的成员信息使得软件难以成为个人信息通讯的替代品

希望开发者尽快解决。

设想：所有成员列表不可见，新注册的成员可以通过其他方式获得想聊天对象的ID或者用户名，通过查找，申请，通过好友的方式建立通讯连接。

以上！

**Comment by suhan1996** [comment]
通过群来加好友，是否能满足需求？

**Comment by ray0019** [comment]
> 对非admin成员隐藏server成员页面，但保留群成员页面，通过群来加好友，是否能满足需求？

最好的设想还是通过搜索用户ID或者用户名来进行添加。如果通过群添加好友，依然非常尴尬，首先得先拉一个群？

**Comment by zerosoul** [comment]
按照 LINE 的加好友逻辑做了一版
