### ISSUE TITLE
[BUG] 一些 Text 错字及翻译问题

### ISSUE THREAD

**Issue by AlanYe-Dev** [Privoce/vocechat-web#72]
**描述问题**
Web 端存在一些文本错字

1. 邀请 "连接" 应改为 "链接"
<img width="451" alt="image" src="https://user-images.githubusercontent.com/45558679/212788161-afec92fd-f03a-4991-ab8e-0531218b6172.png">

2. Github 应改为 GitHub (大小写错误)
<img width="442" alt="image" src="https://user-images.githubusercontent.com/45558679/212788280-7c4b5a5c-60f6-4c22-9716-7d4afa5cfcfa.png">

3. App 端即使把语言改为简体中文，编辑后的文字提示依旧会显示为 (edited)

4. 建议新增对繁体中文的支持

**Comment by zerosoul** [comment]
感谢反馈，前两个已改，第三个转给了APP开发人员，第四个欢迎贡献翻译，目录在：`/public/locales`

**Comment by AlanYe-Dev** [comment]
有一些建议，目前中文只有 zh 一个命名符，建议将所有目前的 zh 重命名为 zh-s 或者 zh_CN，否则和繁体中文 zh-t 或者 zh_TW/zh_HK 不好区分
