### ISSUE TITLE
[FEAT] 建议新增对黑暗模式的支持

### ISSUE THREAD

**Issue by AlanYe-Dev** [Privoce/vocechat-web#73]
**简述**
建议在 Web 端与 App 端新增对于黑暗模式的支持

**你预期要达到什么效果**
黑暗模式可参考 Discord，但我想必开发人员应该知道 Discord 的 UI 界面（？

**目前有没有替代**
你的想法在某个产品中，是否已经有了，请列出
- Discord
- KOOK (开黑啦)

**附加信息**
你的想法的截图，或者您的联系方式，等等
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/45558679/212789773-8047ef15-d410-4773-8e1c-110faf7157f2.png">

**Comment by zerosoul** [comment]
已发版，可以体验下~
