### ISSUE TITLE
网页挂件是否可以增加匿名登录直接建立聊天的功能

### ISSUE THREAD

**Issue by Developer024** [Privoce/vocechat-web#78]
**简述**
目前网页挂件好像只有添加第三方登录的方式才能发起对话，我想能不能增加一个不通过第三方登录的方式来建立对话。
就是相当于一个客服系统

**你预期要达到什么效果**
可以用在商业项目上，做网页接待

**目前有没有替代**
类似于Crisp，国内的飞鱼客服，美恰客服

**Comment by suhan1996** [comment]
Will consider this.

**Comment by zerosoul** [comment]
@Developer024   我们针对widget做了一次迭代，可以通过用户名和邮箱登录
