### ISSUE TITLE
[BUG] docker私有部署，管理员账号注册后进入首页一直loading，网络正常

### ISSUE THREAD

**Issue by crendy** [Privoce/vocechat-web#80]
**描述问题**
docker 部署后，打开设置管理员账号没问题，登录后进入聊天首页一直loading进不去，停止容器就可以进入聊天首页，然后再打开容器可以使用，重新刷新页面还是一直loading。（网络是没问题的）

**如何复现**
复现步骤举例：
1. 部署docker
2. 打开然后注册管理员账号
3. 进入首页，一直loading
<img width="376" alt="image" src="https://user-images.githubusercontent.com/6448115/217979344-c41da456-a118-49c5-8b66-47b292a095df.png">
4. 停止docker容器，会进入首页
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/6448115/217979393-deb3799d-6a6b-4727-854f-f27aeaab5f98.png">
5.再刷新页面后 还是回到第3步的情况（一直loading）。

**预期结果**
可以正常快速进入聊天首页

**环境信息**
-docker 部署在 极空间 nas
-内网穿透使用的 ddnsto
 - 使用环境-操作系统:mac pro  
 - 浏览器： chrome
 - 版本 服务端 latest

**Comment by zerosoul** [comment]
有没有可以对外访问的地址  我进去想看看  方便的话 可以加我V先了解下 yanggc_2013

**Comment by crendy** [comment]
> 有没有可以对外访问的地址 我进去想看看 方便的话 可以加我V先了解下 yanggc_2013

好的
