### ISSUE TITLE
[FEAT]消息排列，自己发的消息能在右侧吗

### ISSUE THREAD

**Issue by zero5652pzj** [Privoce/vocechat-web#81]
**简述**
参考微信、telegram，自己发送的消息在右侧显示。现在voce的消息都是在左侧，使得阅读的时候并不是很方便。

**你预期要达到什么效果**
本人发送的消息在右侧显示

**目前有没有替代**
微信、telegram

**附加信息**
你的想法的截图，或者您的联系方式，等等

**Comment by zerosoul** [comment]
最新版已可以设置 
<img width="798" alt="image" src="https://github.com/Privoce/vocechat-web/assets/2985895/f2a2673d-9919-4117-b8e4-4910ec19aee3">
