### ISSUE TITLE
[BUG] 消息内容并未做加密处理 直接能抓包解析

### ISSUE THREAD

**Issue by pluszhou** [Privoce/vocechat-web#82]
![image](https://user-images.githubusercontent.com/21285312/219349224-eb83d551-f171-4087-92b3-435287160582.png)

**Comment by f0re1gnKey** [comment]
把SSL干的事情搬进业务代码里，您在整个网络界都是独树一帜的

**Comment by ruchid123123** [comment]
抓包就可以看到内容蚌埠住了。
