### ISSUE TITLE
[FEAT] 手机web端有适配的计划吗？最近都没更新了，手机web端体验太差了

### ISSUE THREAD

**Issue by crendy** [Privoce/vocechat-web#89]
**简述**
手机web端有适配的计划吗？最近都没更新了，手机web端体验太差了

**你预期要达到什么效果**
手机web端可以达到类似原生的体验

**Comment by zerosoul** [comment]
手机web已经做了适配，可能在某些机型上，体验还有问题，请问使用的是什么手机以及操作系统版本？
最近web客户端有几次更新，没收到推送吗？我怀疑你现在用的版本比较旧。
可以加我vx yanggc_2013  详细了解下~
