### ISSUE TITLE
[BUG]edge浏览器中聊天页面中ui不对，且点击表情没反应

### ISSUE THREAD

**Issue by libashanxi** [Privoce/vocechat-web#95]
**描述问题**
请用简洁清晰的语言描述您遇到的问题
edge浏览器中聊天页面中ui不对，且打不开表情

**如何复现**
复现步骤举例：
1. 在edge浏览器中打开聊天页面或者安装成应用的方式打开聊天
2. 鼠标放到聊天框的位置，就会发生向右的偏移
3. 且同时鼠标点击表情包没有反应

**预期结果**
请简述预期

**截图**
如果可以，请附上截图（注意保护隐私信息）
鼠标不放在聊天框上，是这样
![image](https://user-images.githubusercontent.com/65264574/224207609-6cbb2756-938f-4ca8-8a39-1136f487fed6.png)
鼠标放在聊天框上就会向右倾斜，像下图这样
![image](https://user-images.githubusercontent.com/65264574/224207756-f9b2715f-8ba0-4c2a-b9eb-f34163d96dcb.png)

**环境信息**
 - 操作系统: [Windows]
 - 浏览器 [edge，版本 110.0.1587.57 (正式版本) (64 位)]
 - 版本 [客户端版本: 0.3.48，服务器端版本: 0.3.3]

**附加信息**
联系方式，备注，等等，可不填

**Comment by zerosoul** [comment]
已确认是用户安装的插件导致的，这种情况难以避免，不属于bug。
