### ISSUE TITLE
[FEAT]手机web版新消息提示 && 聊天对话框建议左右布局的常规方式

### ISSUE THREAD

**Issue by crendy** [Privoce/vocechat-web#97]
**简述**
1.在手机web版增加浏览器新消息提示，目前有信息完全不知道，只能打开相关窗口才能看到，tinode就可以提示，类似这样的：
<img width="378" alt="image" src="https://user-images.githubusercontent.com/6448115/224535951-e9830f4c-6430-4ab7-b7e4-8f71541b45be.png">

2.聊天对话框目前自己和对话方都居左显示，在没有头像设定的情况下，自己的消息很难区分，建议布局类似常规im的左右布局方式。

**Comment by zerosoul** [comment]
第一个需求我们考虑下
