### ISSUE TITLE
[BUG]页面样式调整以及网页挂件的问题

### ISSUE THREAD

**Issue by TTT-TD** [Privoce/vocechat-web#98]
**描述问题**
1. 希望调整页面除版权部分保留信息外使用【服务器名】替换页面中的VoceChat，在wwwroot/locales/zh/Welcome.json中可以使用的{{name}}变量在Auth.json中不可用
2. 访客使用网页挂件时输入已存在的邮箱地址点击聊天没有反应

**如何复现**
复现步骤举例：
访问网页挂件，填入已存在的邮箱地址

**预期结果**
---

**截图**
---

**环境信息**
 - 操作系统: Debian 11
 - 浏览器 Microsoft Edge v109
 - 版本 客户端v0.3.48，服务端v0.3.3

**附加信息**

**Comment by zerosoul** [comment]
第二个问题：已经把邮箱的输入去掉了，现在更便捷了，只需要输入一个用户名
